# Generated by Django 5.2 on 2025-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('int_idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('str_tipo', models.CharField(choices=[('A', 'Alumno'), ('D', 'Docente')], default='A', max_length=1)),
                ('dt_fecha', models.DateField()),
                ('str_estado', models.CharField(choices=[('P', 'Presente'), ('T', 'Tardanza'), ('F', 'Falta'), ('J', 'Justificada')], default='F', max_length=1)),
                ('str_observacion', models.TextField(blank=True, null=True)),
                ('dt_hora_registro', models.TimeField(auto_now_add=True)),
                ('bool_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
            },
        ),
    ]
