# Generated by Django 5.2 on 2025-04-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('asistencia', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='int_idAlumnoSeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='inscripciones.alumnoseccion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='int_idSesionClase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.sesionclase'),
        ),
    ]
