# Generated by Django 5.2 on 2025-04-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_calendario_unique_together_and_more'),
        ('asistencia', '0003_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('int_idCodigoQR', models.AutoField(primary_key=True, serialize=False)),
                ('str_codigo', models.CharField(max_length=255, unique=True)),
                ('dt_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dt_fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('bool_activo', models.BooleanField(default=True)),
                ('int_idSesionClase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='academico.sesionclase')),
                ('str_idDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='usuarios.docente')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'db_table': 'codigo_qr',
            },
        ),
    ]
