# Generated by Django 5.2 on 2025-04-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteSeccion',
            fields=[
                ('int_idDocenteSeccion', models.AutoField(primary_key=True, serialize=False)),
                ('str_tipo', models.CharField(choices=[('P', 'Principal'), ('A', 'Auxiliar'), ('J', 'Jefe de Práctica')], default='P', max_length=1)),
                ('dt_fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('bool_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignación de Docente',
                'verbose_name_plural': 'Asignaciones de Docentes',
                'db_table': 'docente_seccion',
            },
        ),
        migrations.CreateModel(
            name='AlumnoSeccion',
            fields=[
                ('int_idAlumnoSeccion', models.AutoField(primary_key=True, serialize=False)),
                ('dt_fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('bool_activo', models.BooleanField(default=True)),
                ('int_idSeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='academico.seccion')),
            ],
            options={
                'verbose_name': 'Inscripción de Alumno',
                'verbose_name_plural': 'Inscripciones de Alumnos',
                'db_table': 'alumno_seccion',
            },
        ),
    ]
