# Generated by Django 5.2 on 2025-04-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('inscripciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoseccion',
            name='str_idAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='alumnoseccion',
            name='str_idCicloAcademico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cicloacademico'),
        ),
        migrations.AddField(
            model_name='docenteseccion',
            name='int_idSeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='academico.seccion'),
        ),
        migrations.AddField(
            model_name='docenteseccion',
            name='str_idCicloAcademico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cicloacademico'),
        ),
        migrations.AddField(
            model_name='docenteseccion',
            name='str_idDocente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnoseccion',
            unique_together={('str_idAlumno', 'int_idSeccion', 'str_idCicloAcademico')},
        ),
        migrations.AlterUniqueTogether(
            name='docenteseccion',
            unique_together={('str_idDocente', 'int_idSeccion', 'str_tipo', 'str_idCicloAcademico')},
        ),
    ]
