# Generated by Django 5.2 on 2025-04-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAcademico',
            fields=[
                ('str_idCicloAcademico', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('str_nombre', models.CharField(max_length=100)),
                ('dt_fecha_inicio', models.DateField()),
                ('dt_fecha_fin', models.DateField()),
                ('int_duracion_semanas', models.PositiveSmallIntegerField()),
                ('bool_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo Académico',
                'verbose_name_plural': 'Ciclos Académicos',
                'db_table': 'ciclo_academico',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('str_idCurso', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('str_nombre', models.CharField(max_length=200)),
                ('int_creditos', models.PositiveSmallIntegerField()),
                ('bool_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('int_idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('str_dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('dt_hora_inicio', models.TimeField()),
                ('dt_hora_fin', models.TimeField()),
                ('str_aula', models.CharField(blank=True, max_length=50, null=True)),
                ('bool_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('int_idSeccion', models.AutoField(primary_key=True, serialize=False)),
                ('str_numero', models.CharField(max_length=10)),
                ('int_capacidad_maxima', models.PositiveSmallIntegerField()),
                ('bool_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'seccion',
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('int_idSesionClase', models.AutoField(primary_key=True, serialize=False)),
                ('dt_fecha', models.DateField()),
                ('str_estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Realizada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('str_tema', models.CharField(blank=True, max_length=200, null=True)),
                ('str_observacion', models.TextField(blank=True, null=True)),
                ('bool_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clase',
                'db_table': 'sesion_clase',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('int_idSyllabus', models.AutoField(primary_key=True, serialize=False)),
                ('str_version', models.CharField(max_length=20)),
                ('str_contenido', models.TextField()),
                ('dt_fecha_creacion', models.DateField(auto_now_add=True)),
                ('dt_fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabus',
                'db_table': 'syllabus',
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('int_idCalendario', models.AutoField(primary_key=True, serialize=False)),
                ('dt_fecha', models.DateField()),
                ('str_tipo_dia', models.CharField(choices=[('L', 'Laboral'), ('F', 'Feriado'), ('V', 'Vacaciones'), ('S', 'Fin de Semana')], default='L', max_length=1)),
                ('str_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('bool_laborable', models.BooleanField(default=True)),
                ('str_idCicloAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='academico.cicloacademico')),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
                'db_table': 'calendario',
            },
        ),
    ]
