# Generated by Django 5.2 on 2025-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendario',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='calendario',
            constraint=models.UniqueConstraint(fields=('dt_fecha',), name='unique_fecha_calendario'),
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='str_idCicloAcademico',
        ),
    ]
